// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_blackandwhiteabstractwallpaper_png);    // assets\BlackAndWhiteAbstractWallpaper.png
LV_IMG_DECLARE(ui_img_spectrum_png);    // assets\spectrum.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
